# mcp_demo.py
import os

import sqlalchemy
from mcp.server.fastmcp import FastMCP
from sqlalchemy import text

mcp = FastMCP("Oracle MCP Writer")

ORACLE_URL = os.getenv(
    "ORACLE_URL",
    "oracle+oracledb://demo:demo123@oracledb19c-oracle-db.oracle19C.svc.cluster.local:1521/?service_name=orclpdb1"
)

# ORACLE_URL = os.getenv(
#     "ORACLE_URL",
#     "oracle+oracledb://demo:demo123@localhost:59043/?service_name=orclpdb1"
# )

engine = sqlalchemy.create_engine(ORACLE_URL, future=True)

FIXED_OTP = "123456"

# ----- Tool 1: Verify OTP -----
@mcp.tool()
def verify_otp(otp: str) -> dict:
    """
    Verifies the OTP without creating any leave request.
    Returns status only.
    """
    if otp == FIXED_OTP:
        return {"status": "verified"}
    else:
        return {"status": "failed", "error": "Invalid OTP"}

# ----- Tool 2: Create Leave Request -----
@mcp.tool()
def create_leave_request(user_id: str, start_date: str, end_date: str, leave_type: str, reason: str = "") -> dict:
    """
    Creates a leave request in Oracle database.
    Assumes OTP has been verified already.
    The request_id is automatically generated by the DB trigger.
    """
    insert_sql = text("""
        INSERT INTO leave_requests
          (user_id, start_date, end_date, leave_type, reason, status, created_at)
        VALUES (:uid, TO_DATE(:s, 'YYYY-MM-DD'), TO_DATE(:e, 'YYYY-MM-DD'), :t, :r, 'Pending', SYSTIMESTAMP)
        RETURNING request_id INTO :rid
    """)

    try:
        with engine.begin() as conn:
            # Bind variable to capture the generated request_id
            out_param = sqlalchemy.bindparam("rid", type_=sqlalchemy.Integer, outparam=True)
            result = conn.execute(
                text("""
                    BEGIN
                        INSERT INTO leave_requests
                          (user_id, start_date, end_date, leave_type, reason, status, created_at)
                        VALUES (:uid, TO_DATE(:s, 'YYYY-MM-DD'), TO_DATE(:e, 'YYYY-MM-DD'), :t, :r, 'Pending', SYSTIMESTAMP)
                        RETURNING request_id INTO :rid;
                    END;
                """),
                {"uid": user_id, "s": start_date, "e": end_date, "t": leave_type, "r": reason, "rid": out_param}
            )
            rid_value = result.out_parameters["rid"]

        return {"status": "created", "request_id": rid_value}

    except Exception as e:
        return {"error": str(e), "status": "failed"}

